
###
GET http://localhost:1337/habits

###
POST http://localhost:1337/habits
Content-Type: application/json

{
  "title": "english",
  "description": "my first todo",
  "colour": "Blue"
}

###
GET http://localhost:1337/habits/setup


###
POST http://localhost:1337/api/habits/setup
